# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        include: 
          #- os: ubuntu-latest
         #   build-dir: build
          - os: macos-latest
            build-dir: build
        # - os: windows-latest
        #    build-dir: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup CMake & Ninja 
      - name: Setup Cmake and Ninja
        uses: lukka/get-cmake@latest
        
          
      # Setup compilers on Linux and macOS (Windows MSVC is pre-setup in the image)
  
      - name: Setup Clang on macOS
        if: matrix.os == 'macos-latest'
        run: brew install pkg-config glew glfw
  
      # Create build directory
      - name: Create Build Directory
        run: mkdir ${{ matrix.build-dir }}
  
      # Configure CMake
      - name: Configure CMake
        run: cmake -S . -B ${{ matrix.build-dir }} -G "Ninja"
  
      # Build project
      - name: Build
        run: cmake --build ${{ matrix.build-dir }} --verbose

    